# Generated by Django 5.2.7 on 2025-11-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraditionpackage',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Изображение штрихкода'),
        ),
    ]
