# Generated by Django 5.2.7 on 2025-11-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_extraditionpackage_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraditionpackage',
            name='barcode_image',
        ),
    ]
