# Generated by Django 5.2.7 on 2025-11-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена за кг (историческая)'),
        ),
    ]
