# Generated by Django 5.2.7 on 2025-11-20 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_receipt_price_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcode',
            name='status',
            field=models.CharField(choices=[('user_added', 'Добавлен пользователем'), ('warehouse_cn', 'На складе в Китае'), ('shipped_cn', 'Отправлен из Китая'), ('delivered', 'Доставлен'), ('ready', 'Готов к выдаче'), ('claimed', 'Выдан')], max_length=20, verbose_name='Статус трек-кода'),
        ),
        migrations.AlterField(
            model_name='trackcode',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
