# Generated by Django 5.2.7 on 2025-11-23 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_alter_trackcode_status_alter_trackcode_update_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя владельца'),
        ),
        migrations.AlterField(
            model_name='trackcode',
            name='status',
            field=models.CharField(choices=[('no_owner', 'Нет владельца товара'), ('user_added', 'Добавлен пользователем'), ('warehouse_cn', 'Прибыло на склад (Китай)'), ('shipped_cn', 'Отправлено со склада (Китай)'), ('delivered', 'Доставлен на сортировочный склад'), ('ready', 'Доставлен на ПВЗ'), ('claimed', 'Выдано клиенту')], max_length=20, verbose_name='Статус трек-кода'),
        ),
    ]
