# Generated by Django 5.2.7 on 2025-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
