# Generated by Django 5.2.7 on 2025-11-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_is_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('pickup', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
